Renaming a variable to avoid conflict
"__pause" conflicts with:
/usr/lib/gcc/x86_64-linux-gnu/4.8/include/ia32intrin.h:159:1: error: previous declaration of ‘void __pause()’

 __pause (void)